# Generated by Django 2.1.1 on 2018-09-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180928_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(default='null_name', max_length=64, unique=True, verbose_name='角色名')),
                ('role_code', models.CharField(max_length=64, unique=True)),
                ('role_description', models.CharField(max_length=1024, null=True, verbose_name='角色描述')),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_code', models.CharField(blank=True, max_length=64, verbose_name='用户角色标识')),
                ('pm_code', models.CharField(max_length=64, verbose_name='权限标识')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('role_codes', models.CharField(default=None, max_length=256, verbose_name='用户角色code')),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='age',
            new_name='user_age',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='gender',
            new_name='user_gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='null_name', max_length=64, verbose_name='姓名'),
        ),
    ]
