# Generated by Django 2.1.1 on 2018-09-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('err_msg', models.CharField(max_length=10240, verbose_name='错误信息')),
                ('log_type', models.CharField(max_length=64, verbose_name='日志类型')),
                ('err_keyword', models.CharField(max_length=128, verbose_name='错误信息关键字')),
                ('solution', models.TextField(verbose_name='解决方案')),
            ],
        ),
    ]
