# Generated by Django 2.1.1 on 2018-10-07 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180929_2035'),
        ('logAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_name', models.CharField(max_length=126, verbose_name='日志文件名')),
                ('log_path', models.FilePathField(path='./log_files', verbose_name='文件路径')),
                ('upload_user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
